#!/usr/bin/bash
#
#   @@@@@@@@  @@@@@@@   @@@@@@@@  @@@ @@@   @@@@@@    @@@@@@@   @@@@@@   @@@       @@@@@@@@
#  @@@@@@@@@  @@@@@@@@  @@@@@@@@  @@@ @@@  @@@@@@@   @@@@@@@@  @@@@@@@@  @@@       @@@@@@@@
#  !@@        @@!  @@@  @@!       @@! !@@  !@@       !@@       @@!  @@@  @@!       @@!
#  !@!        !@!  @!@  !@!       !@! @!!  !@!       !@!       !@!  @!@  !@!       !@!
#  !@! @!@!@  @!@!!@!   @!!!:!     !@!@!   !!@@!!    !@!       @!@!@!@!  @!!       @!!!:!
#  !!! !!@!!  !!@!@!    !!!!!:      @!!!    !!@!!!   !!!       !!!@!!!!  !!!       !!!!!:
#  :!!   !!:  !!: :!!   !!:         !!:         !:!  :!!       !!:  !!!  !!:       !!:
#  :!:   !::  :!:  !:!  :!:         :!:        !:!   :!:       :!:  !:!   :!:      :!:
#   ::: ::::  ::   :::   :: ::::     ::    :::: ::    ::: :::  ::   :::   :: ::::   :: ::::
#   :: :: :    :   : :  : :: ::      :     :: : :     :: :: :   :   : :  : :: : :  : :: ::
#
#                             .: .bashrc - 2011-03-26 18:46 :.
#
#                  My .bashrc, aliases, bash functions, colors are put in
#              serperate file in ~/.bash/ trying to make some order in caos.
#
#           .: Andreas Persson (greyscale, greu) andreas(at)greyscale(dot)se :.
# __________________________________________________________________________________________
#  This file is distributed "as it is", like it? Then use it in whole or parts of it but be
#   minded that it comes with absolutely no warranty. But then again you got it for free..
# __________________________________________________________________________________________
#

# Check for an interactive session, if not don't do anything.
[ -z "$PS1" ] && return

# The ledgen has foretold that .bashrc can't fight the evil alone and someone's trying to take
# a shortcut. Wake the beaste and invoke ol'mighty .profile first.
#if [ -z "$PROFILE_DONE" ] ; then
#  source ~/.profile && exit
#fi

echo "Reading .bashrc"

# File extraction need extglob
shopt -s extglob

# Check if LINES and COLUMNS needs to be updated.
shopt -s checkwinsize

# Control history (luckily the winner of the war writes it).
shopt -s histappend                                                   # append the history to the histfile instead of overwriting it.
shopt -s cmdhist                                                      # multi-line commands are stored in the history
export HISTFILESIZE=1000                                              # bash history file length
export HISTCONTROL=ignoreboth                                         # no duplicates and empty lines
export HISTIGNORE="&:ls:[bf]g:exit:sudo*:rm*:halt:reboot:shutdown"    # do not store these lines
export VDPAU_NVIDIA_NO_OVERLAY=1                                      # Fix bleeding overlay with Flash
#export PROMPT_COMMAND="history -n; history -a"                       # update & re-read histfile after every cmd so terminals will share


# make less more friendly for non-text input files, see lesspipe(1)
#[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/bash lesspipe)"

export EDITOR='vim'
export VISUAL='vim'
export LS_OPTIONS='--color --group-directories-first'
export GREP_COLOR='38;5;111'
export PAGER='less'
export LESS='-iRFX'
#export LESSOPEN='|/usr/bin/lesspipe.sh %s 2>&-'
#export _JAVA_OPTIONS="-Dawt.useSystemAAFontSettings=on -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel"
export SSH_ENV=$HOME/.ssh/environment
export TIME_STYLE=long-iso                              # Sets the time format for ls to something better.

# Disable XON/XOFF flow control (^s/^q)
stty -ixon

# Source all files in ~/.bash/
for CFGFILE in ~/.bash/*; do
  if [ -r ${CFGFILE} ]; then
    source ${CFGFILE}
  fi
done


# Source SSH settings, if applicable
if [ -f "${SSH_ENV}" ]; then
  source ${SSH_ENV} > /dev/null
  ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
    start_agent;
  }
else
  start_agent;
fi

# vim:fenc=utf-8:ft=sh
# EOF
