#!/usr/bin/bash
#
#   @@@@@@@@  @@@@@@@   @@@@@@@@  @@@ @@@   @@@@@@    @@@@@@@   @@@@@@   @@@       @@@@@@@@
#  @@@@@@@@@  @@@@@@@@  @@@@@@@@  @@@ @@@  @@@@@@@   @@@@@@@@  @@@@@@@@  @@@       @@@@@@@@
#  !@@        @@!  @@@  @@!       @@! !@@  !@@       !@@       @@!  @@@  @@!       @@!
#  !@!        !@!  @!@  !@!       !@! @!!  !@!       !@!       !@!  @!@  !@!       !@!
#  !@! @!@!@  @!@!!@!   @!!!:!     !@!@!   !!@@!!    !@!       @!@!@!@!  @!!       @!!!:!
#  !!! !!@!!  !!@!@!    !!!!!:      @!!!    !!@!!!   !!!       !!!@!!!!  !!!       !!!!!:
#  :!!   !!:  !!: :!!   !!:         !!:         !:!  :!!       !!:  !!!  !!:       !!:
#  :!:   !::  :!:  !:!  :!:         :!:        !:!   :!:       :!:  !:!   :!:      :!:
#   ::: ::::  ::   :::   :: ::::     ::    :::: ::    ::: :::  ::   :::   :: ::::   :: ::::
#   :: :: :    :   : :  : :: ::      :     :: : :     :: :: :   :   : :  : :: : :  : :: ::
#
#    .: FILE:          nautilus
#    .: CREATED:       2011-04-30 01:31
#    .: AUTHOR:        Andreas Persson (greyscale, grey)
#    .: MAIL:          <andreas(at)greyscale(dot)se>
#    .: VERSION:       1.0
#    .: DESCRIPTION:   Dropbox opens nautilus when you open your dropbox folder
#                      from the client, this scripts just take the location of
#                      the folder and opens it in pcmanfm-mod instead.
#
# __________________________________________________________________________________________
#  This file is distributed "as it is", like it? Then use it in whole or parts of it but be
#  minded that it comes with absolutely no warranty. But then again you got it for free..
# __________________________________________________________________________________________
#


exec pcmanfm-mod $@
exit 0
