#!/bin/bash
#
#   @@@@@@@@  @@@@@@@   @@@@@@@@  @@@ @@@   @@@@@@    @@@@@@@   @@@@@@   @@@       @@@@@@@@
#  @@@@@@@@@  @@@@@@@@  @@@@@@@@  @@@ @@@  @@@@@@@   @@@@@@@@  @@@@@@@@  @@@       @@@@@@@@
#  !@@        @@!  @@@  @@!       @@! !@@  !@@       !@@       @@!  @@@  @@!       @@!
#  !@!        !@!  @!@  !@!       !@! @!!  !@!       !@!       !@!  @!@  !@!       !@!
#  !@! @!@!@  @!@!!@!   @!!!:!     !@!@!   !!@@!!    !@!       @!@!@!@!  @!!       @!!!:!
#  !!! !!@!!  !!@!@!    !!!!!:      @!!!    !!@!!!   !!!       !!!@!!!!  !!!       !!!!!:
#  :!!   !!:  !!: :!!   !!:         !!:         !:!  :!!       !!:  !!!  !!:       !!:
#  :!:   !::  :!:  !:!  :!:         :!:        !:!   :!:       :!:  !:!   :!:      :!:
#   ::: ::::  ::   :::   :: ::::     ::    :::: ::    ::: :::  ::   :::   :: ::::   :: ::::
#   :: :: :    :   : :  : :: ::      :     :: : :     :: :: :   :   : :  : :: : :  : :: ::
#
#    .: FILE:          nightmode
#    .: CREATED:       2011-11-05 23:54
#    .: AUTHOR:        Andreas Persson (greyscale, grey)
#    .: MAIL:          <andreas(at)greyscale(dot)se>
#    .: VERSION:       1.0
#    .: DESCRIPTION:   Starts redshift and adjusts the color temperature of your screen
#                      according to your surroundings.
#
# __________________________________________________________________________________________
#  This file is distributed "as it is", like it? Then use it in whole or parts of it but be
#  minded that it comes with absolutely no warranty. But then again you got it for free..
# __________________________________________________________________________________________
#

# Latitude:Longitude
LATLON=56.28:13.7

case $1 in
  "-k")
    # Kill running redshift.
    pkill redshift
    ;;
  *)
    # Start if not already running.
    if [ -z "$(pgrep redshift)" ]; then
      redshift -l ${LATLON}  -t 5700:3600 -g 0.8 -m vidmode &
    else
      echo "Redshift already running."
    fi
    ;;
esac
