#!/bin/bash
# 
#    @@@@@@@@  @@@@@@@   @@@@@@@@  @@@ @@@   @@@@@@    @@@@@@@   @@@@@@   @@@       @@@@@@@@
#   @@@@@@@@@  @@@@@@@@  @@@@@@@@  @@@ @@@  @@@@@@@   @@@@@@@@  @@@@@@@@  @@@       @@@@@@@@
#   !@@        @@!  @@@  @@!       @@! !@@  !@@       !@@       @@!  @@@  @@!       @@!
#   !@!        !@!  @!@  !@!       !@! @!!  !@!       !@!       !@!  @!@  !@!       !@!
#   !@! @!@!@  @!@!!@!   @!!!:!     !@!@!   !!@@!!    !@!       @!@!@!@!  @!!       @!!!:!
#   !!! !!@!!  !!@!@!    !!!!!:      @!!!    !!@!!!   !!!       !!!@!!!!  !!!       !!!!!:
#   :!!   !!:  !!: :!!   !!:         !!:         !:!  :!!       !!:  !!!  !!:       !!:
#   :!:   !::  :!:  !:!  :!:         :!:        !:!   :!:       :!:  !:!   :!:      :!:
#    ::: ::::  ::   :::   :: ::::     ::    :::: ::    ::: :::  ::   :::   :: ::::   :: ::::
#    :: :: :    :   : :  : :: ::      :     :: : :     :: :: :   :   : :  : :: : :  : :: ::
# 
#     .: FILE:          vim-colorschemeeditor
#     .: CREATED:       2012-04-08 19:53
#     .: AUTHOR:        Andreas Persson (greyscale, grey)
#     .: MAIL:          <andreas(at)greyscale(dot)se>
#     .: VERSION:       1.0
#     .: DESCRIPTION:   Simple wrapper to run vim-colorschemeeditor since i'm not likely
#                       to remember what paths etc it want tomorrow...
# 
#  __________________________________________________________________________________________
#   This file is distributed "as it is", like it? Then use it in whole or parts of it but be
#   minded that it comes with absolutely no warranty. But then again you got it for free..
#  __________________________________________________________________________________________
# 

python2 /usr/share/vim/vimfiles/plugin/ColorSchemeEditor.py NONE /usr/share/vim/vimfiles/plugin
