#!/in/bash - 
#===============================================================================
#
#					 FILE:	alias
# 
#					USAGE:	sourced from "/.bashrc
# 
#		DESCRIPTION:	Sets the aliases for bash
# 
#				 AUTHOR:	Andreas Persson andreas(at)greyscale(dot)se
#				
#				CREATED:	2011-03-26 18:26
#
#===============================================================================
#

# Nice alias to have.
alias egrep='egrep --color=auto'
alias grep='grep --color=auto'
alias vi='vim'
alias xlock='xscreensaver-command --lock'
alias xblank='xscreensaver-command -a'
alias xterm='uxterm'
alias diff='colordiff'
alias more='less'
alias df='df -h'
alias du='du -h'
#alias dmesg='colored_dmesg'

alias ls='ls --group-directories-first --color=always -h -F'
alias lsc='ls --color=always'
alias ll='ls -l'
alias la='ls -la'
alias l='ls -CF'
alias lx='ll -BX'												# sort by extension
alias lz='ll -rS'												# sort by size
alias lt='ll -rt'												# sort by date
alias bxterm='xterm -bg black -fg grey'

alias mc='mc -u'												# Workaround for mc's sloow startup.

# Pacman alias examples
alias pacman='pacman-color'
alias pacupg='sudo pacman -Syu'					# Synchronize with repositories before upgrading packages that are out of date on the local system.
alias pacin='sudo pacman -S'						# Install specific package(s) from the repositories
alias pacins='sudo pacman -U'						# Install specific package not from the repositories but from a file 
alias pacre='sudo pacman -R'						# Remove the specified package(s), retaining its configuration(s) and required dependencies
alias pacrem='sudo pacman -Rns'					# Remove the specified package(s), its configuration(s) and unneeded dependencies
alias pacrep='pacman -Si'								# Display information about a given package in the repositories
alias pacreps='pacman -Ss'							# Search for package(s) in the repositories
alias pacloc='pacman -Qi'								# Display information about a given package in the local database
alias paclocs='pacman -Qs'							# Search for package(s) in the local database

# vim:fenc=utf-8:ft=sh
