#!/bin/bash
#
#   @@@@@@@@  @@@@@@@   @@@@@@@@  @@@ @@@   @@@@@@    @@@@@@@   @@@@@@   @@@       @@@@@@@@
#  @@@@@@@@@  @@@@@@@@  @@@@@@@@  @@@ @@@  @@@@@@@   @@@@@@@@  @@@@@@@@  @@@       @@@@@@@@
#  !@@        @@!  @@@  @@!       @@! !@@  !@@       !@@       @@!  @@@  @@!       @@!
#  !@!        !@!  @!@  !@!       !@! @!!  !@!       !@!       !@!  @!@  !@!       !@!
#  !@! @!@!@  @!@!!@!   @!!!:!     !@!@!   !!@@!!    !@!       @!@!@!@!  @!!       @!!!:!
#  !!! !!@!!  !!@!@!    !!!!!:      @!!!    !!@!!!   !!!       !!!@!!!!  !!!       !!!!!:
#  :!!   !!:  !!: :!!   !!:         !!:         !:!  :!!       !!:  !!!  !!:       !!:
#  :!:   !::  :!:  !:!  :!:         :!:        !:!   :!:       :!:  !:!   :!:      :!:
#   ::: ::::  ::   :::   :: ::::     ::    :::: ::    ::: :::  ::   :::   :: ::::   :: ::::
#   :: :: :    :   : :  : :: ::      :     :: : :     :: :: :   :   : :  : :: : :  : :: ::
#
#    .: FILE:           eyecandy
#    .: CREATED:        2011-03-26 18:42
#    .: AUTHOR:         Andreas Persson (greyscale, grey)
#    .: MAIL;           <andreas(at)greyscale(dot)se>
#    .: VERSION:        1.0
#    .: REVISION:       ---
#    .: DESCRIPTION:    
#
# __________________________________________________________________________________________
#  This file is distributed "as it is", like it? Then use it in whole or parts of it but be
#  minded that it comes with absolutely no warranty. But then again you got it for free..
# __________________________________________________________________________________________
#

# Pretty colors in less and man pages.
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'

# cwapper color settings
export CW_COLORIZE=blue:purple

# Colors for ls
if [ -e ~/.dircolors-256grayvim ]; then
    eval $(/bin/dircolors -b ~/.dircolors-256grayvim)
fi

# Change console color theme.
echo -en "\e]P0121212"
echo -en "\e]P1ff0056"
echo -en "\e]P2a0eb01"
echo -en "\e]P3fcf330"
echo -en "\e]P45fafff"
echo -en "\e]P5ff8700"
echo -en "\e]P6808080"
echo -en "\e]P7e4e4e4"
echo -en "\e]P81c1c1c"
echo -en "\e]P9ff00ac"
echo -en "\e]Pa5fd700"
echo -en "\e]Pbffd700"
echo -en "\e]Pc87afff"
echo -en "\e]Pdff5400"
echo -en "\e]Pe5fffff"
echo -en "\e]Pfe4e4e4"

# vim:fenc=utf-8:ft=sh
