#!/bin/bash - 
#===============================================================================
#
#          FILE:  prompt
# 
#         USAGE:  sourced from "/.bashrc
# 
#   DESCRIPTION:  Sets the prompt for bash with some nice colors etc.
# 
#        AUTHOR:  Andreas Persson andreas(at)greyscale(dot)se
#       COMPANY: 
#       CREATED:  02/20/2011 12:38:27 PM CET
#
#===============================================================================

# export PS1='\[\e[1;32m\][\[\e[1;34m\]\t\[\e[1;32m\]]\[\e[1;32m\][\[\e[1;34m\]\u\[\e[1;32m\]@\[\e[1;34m\]\h \[\e[1;34m\]\w\[\e[1;32m\]]\[\e[1;32m\]\$\[\e[m\] '
export PS1='\[\e[0;35m\][\[\e[0;34m\]\t\[\e[0;35m\]]\[\e[0;35m\][\[\e[0;34m\]\u\[\e[0;35m\]@\[\e[0;34m\]\h \[\e[0;34m\]\w\[\e[0;35m\]]\[\e[0;35m\]\$\[\e[m\] '

# vim:fenc=utf-8:ft=sh
